swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Petstore
consumes: [application/json]
produces: [application/json]
paths:
  /pets:
    get:
      responses:
        "200":
          description: pet response
          schema:
            type: string
        default:
          description: unexpected error
          schema:
            $ref: string
